# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generic method for the imzMLreader
#' testingimzMLBinRead
#' @param ibdFname: full path to the ibd file.
#' @param NPixels: Total number of pixels in the image.
#' @param N: number of elemetns (or data point to read).
#' @param offset: offset in bytes at which the reading operation is started.
#' @param read_mz: if true m/z data is readed, otherwise intensities are readed.
#' @param continuous: true if imzML data is in continuous mode
imzMLBinReadGeneric <- function(ibdFname, NPixels, N, offset, dataTypeString, read_mz, continuous) {
    .Call('_MsBackendImzML_imzMLBinReadGeneric', PACKAGE = 'MsBackendImzML', ibdFname, NPixels, N, offset, dataTypeString, read_mz, continuous)
}

CimzMLParse <- function(xml_path) {
    .Call('_MsBackendImzML_CimzMLParse', PACKAGE = 'MsBackendImzML', xml_path)
}

